### ISSUE TITLE
Corregir validación del campo Rut en formulario HTML

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#1]
## Descripción
El patrón de validación actual del campo Rut en el formulario HTML permite ingresar un Rut incorrecto con dos guiones
 (por ejemplo, 9-9). Esto puede causar confusiones y errores en la introducción de datos por parte de los usuarios.

## Acción requerida
Modificar el patrón de validación del campo Rut para asegurar que solo se permita un guion y en la posición correcta, después del penúltimo dígito.

## Codigo register.astro
```html
    <label for="Rut">Rut</label>
    <input
      type="text"
      name="Rut"
      id="Rut"
      placeholder="Ingresa tu Rut sin puntos y con guión"
      pattern="^0*(\\d{1,3}(\\.?\\d{3})*)-([\\dkK])$"
      title="Ingresa un Rut válido (por ejemplo, 12345678-K)"
      required
      maxlength="10"
    />
```

**Comment by Javieers** [comment]
Corregido, detecta que el guion esté en el lugar correcto, tanto para-Rut con 7 y 8 dígitos antes del guion.

`<label for="Rut">Rut</label>
<input
  type="text"
  name="Rut"
  id="Rut"
  placeholder="Ingresa tu Rut sin puntos y con guión"
  pattern="^\\d{7,8}-[\\dkK]$"
  title="Ingresa un Rut válido (por ejemplo, 12345678-K o 1234567-K)"
  required
  maxlength="10"
/>`
