### ISSUE TITLE
Dejar visible boton "Cerrar Sesión" en pagina de testimonio

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#12]
# Descripción

Tomando el caso que dejo @Perrla1 En la pagina del testimonio hay que dejar visible el botón de cerrar sesión ya implementado en el documento que nos entrego astro docs

# Evidencias

https://github.com/vicenteroa/CardioCare-IA/assets/79950811/c50c73cc-1968-4ad7-8f59-73d1b015f572

# Tareas 

1. Intentar mover la lógica al componente de sidebar 
2. Aplicar CSS en la etiqueta del botón para traerlo al frente del componente del sidebar
3. Agregarle SVG del icono sesión

**Comment by Javieers** [comment]
Solucionado
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/09b52664-70a6-4b46-969c-6bede6fcb26b)
