### ISSUE TITLE
Añadir boton "Ver y Ocultar Contraseña"👁️

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#15]
# Descripción
Se ha observado que la pagina actualmente no tiene un boton que el usuario pueda verificar su contraseña tanto al registrarse como al iniciar sesión 

# Evidencias

### Login
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/cccbc353-a2df-4984-b806-7f7568e31bfd)
### Register
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/1546d742-a3c8-42ed-b0ee-00b193a14ee5)

# Tareas a realizar
1. Modificar si es necesario o añadir el icono estándar para poder ver y ocultar la contraseña 
2. Idealmente utilizar [ionicons](https://ionic.io/ionicons)
3. Realizar la logica para cambiar el tipo de input de "password" a "text" 
4. Realizar la logica para intercalar los iconos de Ver y Ocultar 
5. Realizar pruebas

**Comment by Javieers** [comment]
Se agrega boton para ver y ocultar contraseña, tanto en el registro de usuario como en el inicio de sesión.
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/b43f89fc-0715-4445-ac5f-172298f26754)
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/3ebc2b01-0d26-4c10-9a12-248459d59632)
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/acd87213-9db4-45fe-a12b-274491d0750b)
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/0d5bee8e-c02e-47f8-acba-b62b250daf03)
