### ISSUE TITLE
Error botón Cerrar sesión

### ISSUE THREAD

**Issue by Javieers** [vicenteroa/CardioCare-IA#17]
# Descripción
El botón de Cerrar sesión en la ventana de testimonio ("dashboard.astro") no funciona correctamente, ya que al presionarlo no ocurre nada.

# Evidencias
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/1a1d2b12-b232-46ee-b5b9-5f4f13a362c9)

# Tareas a realizar
1. Revisar códigos anteriores, ya que antes si funcionaba.

**Comment by thewizardshell** [comment]
# Descripción
Revisando el codigo anterior he encontrado que una linea del codigo ha sido borrado para que el boton del "Cerrar sesion" no funcionase 

# Evidencia
![error1](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/d7cdf9a6-4a2b-403a-8d30-763d7b7a1cb2)

Como se puede observar la etiqueta `<from>` no esta iniciada si no que solo cerrada , esto muy importante ya que esta etiqueta manda y recibe la solicitud de la api de singout para poder cerrar la sesión y eliminar la cookie 

# Solución
![error1-2](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/708e8350-a681-41bc-85ed-d1304935e1f7)
