### ISSUE TITLE
Error Tema Oscuro en testimonio

### ISSUE THREAD

**Issue by Javieers** [vicenteroa/CardioCare-IA#18]
# Descripción
En la ventana de testimonio ("dashboard.astro") el modo oscuro funciona con errores, ya que al activarlo el texto queda completamente blanco, ya que su color de origen es negro.

# Evidencias

### Modo claro
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/ff3b1843-8294-45e6-a921-8913e6ff4e12)

### Modo oscuro
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/fd5fd79b-3ad4-4db6-91e6-2cf26459133b)

**Comment by thewizardshell** [comment]
# Descripción
Faltaba la integración con las variables de css que hacen el cambio de color de tema oscuro a claro

# Solución
### CSS
Se agregaron estos estilos el estilo` var(--background-color)` es el que hace el efecto para utilizar el fondo claro y oscuro de manera correcta sin esta variable es imposible ver cambios de tema de color, por otro lado el `var(--background-color-dark`) es otro tipo de negro que se puede aplicar al modo oscuro pero necesita de un `:global` por lo que el contenedor del formulario tambien cambia, esto mas que nada para que haya un contraste entre el formulario y el fondo
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/8529575d-c540-405f-8c91-58f12c658471)
### HTML
Se agrego una etiqueta `main` al principio del html que sera el que controla el tema oscuro y claro
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/6248718d-3275-4034-a3a6-a5224d355959)


# Evidencia

https://github.com/vicenteroa/CardioCare-IA/assets/79950811/f4dada49-7b44-432a-be97-47abb0bd9c49

# EXTRA

> [!NOTE]
> Agregue la sombra a la imagen del doctor
>
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/e881f491-9f6d-402f-8e33-3e16074e56ab)
