### ISSUE TITLE
Reporte de Error: Box Fuera del Contenedor

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#21]
# Describir el error
Actualmente se ha observado que el botón para aceptar términos y condiciones , se mueve si el usuario le hace zoom a la pagina si existe responsive
# Comportamiento esperado 
Se espera que el contenedor donde esta ubicado el boton con el texto se mueva junto al contenedor de adentro y no queda por fuera.

# Evidencia
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/3df1f4b1-fad7-4302-bd91-62db00f4d825)

**Comment by Javieers** [comment]
Corregido, el botón está dentro del cuadro, además la imagen de la doctora ya está en la posición correcta.
![image](https://github.com/vicenteroa/CardioCare-IA/assets/85529722/4bb20e59-fd82-41e6-84b4-c54d791b7cab)
