### ISSUE TITLE
Problema de carga de imagen del icono en el footer debido a ruta incorrecta

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#3]
# Descripción del problema

En el sitio web de CardioCare-IA [Link](https://cardio-care-ia.vercel.app/), se ha detectado un problema con la visualización del icono en el footer. Al intentar cargar la imagen del icono desde la ruta /public/logo.png, el servidor responde con un código de estado 404, indicando que el recurso no se encuentra disponible.

![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/7f5852a7-81ae-4c82-99f4-6e5bddf134d3)
# Análisis
El error sugiere que la ruta especificada para la imagen del icono no está siendo encontrada correctamente. Actualmente, la ruta parece ser ../../../public//logo.png. Se ha identificado que la presencia de // en la ruta puede ser la causa de este problema.

# Solución Propuesta
Modificar la ruta de la imagen del icono en el código para corregir el problema de carga. Se sugiere cambiar la ruta de la siguiente manera :

> **Consideración!**
> 
> Al momento de corregir el problema localmente con npm run dev y hacer push a la rama master , vercel se encargará de tomar estos cambios y traerlos en unos minutos a la pagina (tiempo aproximado 5 minutos)

Antes: ../../../public//logo.png

Después: ../../../public/logo.png

*Eliminar el doble slash (//) corregirá la ruta y permitirá que la imagen se cargue correctamente desde el directorio especificado.*

**Comment by amxylk31** [comment]
Problema arreglado, se muestra correctamente la imagen del footer.
![2024-05-01 19_24_30-Window](https://github.com/vicenteroa/CardioCare-IA/assets/165733266/5446c69d-5595-4018-81dd-c97cb594f6c5)
