### ISSUE TITLE
404 Design

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#4]
# Descripción

Actualmente, cuando los usuarios acceden a URLs que no existen en el sitio web, se muestra la página de error predeterminada del servidor, lo que puede resultar en una experiencia confusa para los usuarios. Para mejorar esto, se propone crear una página de error 404 personalizada que brinde una experiencia más informativa y amigable.

![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/edde0f02-5a55-43fb-8c8c-ed11c5785305)

# Tareas

1. Crear un 404.astro
2. Diseñar manteniendo la paleta de colores
3. Probar

***el 404.astro es automático no conlleva lógica***

**Comment by thewizardshell** [comment]
# Diseño para el 404
### Modo Claro
#28A7DC
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/76958a42-3ad0-491a-acd3-730ced6850bf)


### Modo Oscuro
#191A1B 
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/77f01d3c-476e-4302-93af-213f54acc13b)

**Comment by bquezadag** [comment]
Se agrego pagina 404.astro
De forma efectiva !!!

**Comment by thewizardshell** [comment]
@Perrla1 
Esta super bieeeen el 404 me gusto aunque lo he modificado un poquito que no quiere decir que haya estado malo si no que mas que nada orden y una cosa que falto, te adjunto tu codigo astro para las comparaciones

# 404.astro Benjamin

```astro
---
import logo from "../../public/logo.png"
---
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #28A7DC;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
			font-size: 19px;
        }
        body.dark {
  	    background-color: #191A1B;
  	    color: #fff;
	    }
        .error-container {
            text-align: center;
            color: white;
            border: 40px solid white;
            padding: 10px;
            display: flex;
			width: 1200px;
            align-items: center;
			text-align: justify;
        }
        .error-container h1 {
            font-size: 65px;
            margin: 10px;
			padding: 10px;
			text-align: center;
        }
		.error-icon {
            margin-right: 20px;
        }

    </style>
</head>
<body>
    <div class="error-container">
        <img class="error-icon" src="/public/logo.png" alt="Logo">
        <div>
            <h1>ERROR 404</h1>
            <p>Lo sentimos, la pagina que estas buscando no se encuentra. Puede que haya sido eliminada o que la direccion este incorrecta.</p>
        </div>
    </div>
</body>
</html>
``` 
Ok mira:

1. Falto de casualidad el componente `Layout.astro` acordarse que layout.astro por defecto ya trae las etiquetas <html> y <body> y es la estructura principal de la pagina por lo que para cualquier archivo no es necesario agregar partiendo con un `<doctype>` o las otras etiquetas mencionadas , en cambio usar el componente Layout.astro
2. Si bien tener el style arriba no es malo , para mantener un el mismo orden de codigo en todas las paginas he movido todo el style al final del codigo

Todo lo demas ✅😉Excelente!!!

Ahora te muestro mis cambios:

# 404.astro Vicente

```astro
---
import logo from "../../public/logo.png"
import Layout from "../layouts/Layout.astro"
---
<Layout title="404">
    <div class="error-container">
        <img class="error-icon" src="/public/logo.png" alt="Logo">
        <div>
            <h1><strong>ERROR 404</strong></h1>
            <p>Lo sentimos, la pagina que estas buscando no se encuentra. Puede que haya sido eliminada o que la direccion este incorrecta.</p>
        </div>
    </div>
</body>
</Layout>

<script is:inline>
    document.addEventListener("DOMContentLoaded", function() {
    const theme = localStorage.getItem('theme');
    if (theme) 
    {
        document.body.className = theme;
    }
    });
</script>

<style>
body {
    background-color: var(--background-color-light); /* Color de fondo para modo claro */
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
    font-size: 19px;
}
html.dark{
    background-color: #191A1B;
    color: #fff 
}
body.dark {
    background-color: #191A1B;
    color: #fff;
}

.error-container {
    text-align: center;
    color: white;
    border: 40px solid white;
    padding: 10px;
    display: flex;
    width: 1200px;
    align-items: center;
    text-align: justify;
}
h1{
    position: relative;
    right: 20vh;
    
}
.error-container h1 {
    font-size: 65px;
    margin: 10px;
    padding: 20px;
    text-align: center;
}

.error-icon {
    margin-right: 1vh;
}
</style>
``` 

Agrege un `<script>`que esto lo que hace es consultar al local storage que tema se esta utilizando por lo que ya **ESTA LISTO EL TEMA CLARO Y OSCURO DE 404.ASTRO**
