### ISSUE TITLE
Icono de CardioCare no clickeable en el header

### ISSUE THREAD

**Issue by thewizardshell** [vicenteroa/CardioCare-IA#6]
# Descripción
Actualmente, en el header se encuentra el icono de CardioCare, pero este no es clickeable para volver a la página principal. Se requiere agregar funcionalidad para que el icono sea clickeable y redirija a la página principal del sitio.

# Evidencias
El click en el logo no devuelve a la pagina principal 
![image](https://github.com/vicenteroa/CardioCare-IA/assets/79950811/aac71adf-b7b7-489c-bcbc-21d563b8fc38)

# Posibles Tareas para Solucionar
1. Modificar el código del header para convertir el icono de CardioCare en un enlace clickeable.
2. Enlazar el icono a la página principal del sitio, de modo que al hacer clic en él se redireccione correctamente.
3. Realizar pruebas para asegurar que el icono sea clickeable y redirija a la página principal en diferentes navegadores y dispositivos.

**Comment by bquezadag** [comment]
Solucionado,
Se agrego icono clickeable con un href ="index.astro"
